### ISSUE TITLE
Whether to expose time in oscillators?

### ISSUE THREAD

**Issue by aatishb** [aatishb/synthesine#3]
I'm thinking through whether to make time explicit in the definition of the oscillators.

### Option 1: (Currently used)

`sin(f)` means `t => Math.sin(2 * PI * f * t)`, i.e. returns a function mapping time to a sine wave

Usage:

```
function setup() {
}

function loop() {
  return time
    .map(sin(440))
    .mult(0.1);
}
```

Pros: flow of data is explicit
Cons: cumbersome syntax, confusing for beginners

### Option 2:

`sin(f)` means `time.map(t => Math.sin(2 * PI * f * t))`, i.e. returns a piece of a sine wave

Usage:

```
function setup() {
}

function loop() {
  return sin(440).mult(0.1);
}

```
Pros: concise, easier syntax
Cons: The time dependence is hidden. You might do the following and expect a sine wave, when in fact you'll just get a tiny piece of the beginning of one, looped. So this might introduce some bugs.

```
let wave;

function setup() {
  wave = sin(440).mult(0.1):
}

function loop() {
  return wave;
}

```

@shefalinayak curious what you think?

**Comment by shefalinayak** [comment]
I think I like the second option, but maybe with an edit:

### Option 3
We've seen `sin(f)` since precalculus as a number or a function and it's not the easiest step to treat it like an object. So I would rename it to something like `sinWave(f)` to make it more obvious it returns a wave object. Then sinWave, squareWave, etc become more building blocks, which I think makes sense since when you think about sound, those are the basic building blocks you think about, rather than time (right?)

So something like this (your adding sine waves example):
```
function loop() {
  myWave = time.map(sin(freq));
  myWave2 = time.map(sin(mult1 * freq));
  myWave3 = time.map(sin(mult2 * freq));

  return myWave
    .add(myWave2)
    .add(myWave3)
    .mult(0.1);
}
```
would become more concise and I think it's clearer that you're adding three sine waves together:

```
function loop() {
  return sinWave(freq)
    .add(sinWave(mult1 * freq))
    .add(sinWave(mult2 * freq))
    .mult(0.1);
}
```

Then you can play with add/sub/mult/div without having to grasp map first. That feels better to me—time and map being one level deeper into the learning process.

About the potential bug you mentioned (`wave = sin(440).mult(0.1)` in setup)—I think the issue might not be about the time dependency, but rather understanding the function of setup vs loop. I looked through the examples and it seems like the only wave you ever define in setup is a zero wave, and any other wave manipulation is in the loop because it has to be updated repeatedly. So maybe an explanation of the coding environment (what setup is for, what loop is for, that you need to return a wave) would be the solution? Whenever you start a new arduino sketch they have comments that explain setup and loop and I think it's pretty helpful.

**Comment by aatishb** [comment]
Thanks @shefalinayak, all excellent points. I like this a lot. Good point about the confusion between sin as a function and wave object!

One nice thing about this approach is that all we have to do is add in some new functions, it doesn't break any old code. :)

So maybe let's add

- [ ] sinWave
- [ ] triWave
- [ ] sawWave
- [ ] sqrWave
- [ ] noiseWave
- [ ] ??? –– [damped sine wave](https://aatishb.com/synthesine/examples/dampedsine/index.html) (super useful for synthesis)

and can rewrite some of the examples to make use of this.

**Comment by aatishb** [comment]
Trying this out in a new branch: https://github.com/aatishb/synthesine/issues/3

**Comment by aatishb** [comment]
Added a .fade prototype to the Wave object, so now we don't need a special dampedSin function, and the syntax is more clear.

```
function loop() {
  return time
    .map(sinDamped(440, 1))
    .mult(0.5);
}
```
becomes
```
function loop() {
  return sinWave(440)
    .fade(0.1)
    .mult(0.5);
}

```
